### ISSUE TITLE
Get TrickFMI listed at the official FMI tools site

### ISSUE THREAD

**Issue by tbeu** [nasa/TrickFMI#1]
Do you fancy to get TrickFMI officially listed at https://fmi-standard.org/tools/? Please consider the [contribution guideline](https://github.com/modelica/fmi-standard.org/blob/master/CONTRIBUTING.md#updating-the-tools-list) for you PR.

**Comment by ezcrues** [comment]
It’s something that I would consider.  I’ll have to review the contribution guidelines.

Thanks.
